name: aminoss_photography
description: Professional Photography Portfolio & Business Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  
  # Media & Camera
  image_picker: ^1.0.5
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # PDF & Documents
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Date & Time
  intl: ^0.18.1
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Permissions
  permission_handler: ^11.1.0
  
  # File Picker
  file_picker: ^6.1.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Pull to Refresh
  pull_to_refresh: ^2.0.0
  
  # Skeleton
  skeletons: ^0.0.3
  
  # Animations
  animate_do: ^3.1.2
  
  # Charts
  fl_chart: ^0.65.0
  
  # Share
  share_plus: ^7.2.1
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Device Info
  device_info_plus: ^9.1.1
  
  # Package Info
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logo/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# App Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
  adaptive_icon_background: "#c67548"
  adaptive_icon_foreground: "assets/logo/app_icon_foreground.png"

# Splash Screen
flutter_native_splash:
  color: "#c67548"
  image: assets/logo/splash_logo.png
  android: true
  ios: true
  android_12:
    color: "#c67548"
    image: assets/logo/splash_logo.png
